import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/homepage/Header";
import Navbar from "@/components/homepage/Navbar";
import Marquee from "@/components/homepage/Marquee";
import Footer from "@/components/homepage/Footer";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
        <Header />
        <Navbar />
        <Marquee />
        <main className="container mx-auto">
          <Suspense fallback={<h2>Loading......</h2>}>
          {children}
          </Suspense>
          </main>
        <Footer />
      </body>
    </html>
  );
}
